[database]
driver ="mysql"
username ="moto"
password = "motomoto"
host = "192.168.0.40"
port = "3306"
dbname = "epgrec"
option = "parseTime=true"

[[excludes]]
keyword = "少年アシベ%"
[[excludes]]
keyword = "チュウキョ〜ちゃん%"
[[excludes]]
keyword = "Ａ応Ｐのあにむす！！%"
[[excludes]]
keyword = "みんなのうた%"
[[excludes]]
keyword = "Ｅテレ０６５５%"
[[excludes]]
keyword = "Ｅテレ２３５５%"
[[excludes]]
keyword = "%おじゃる丸%"
[[excludes]]
keyword = "%忍たま乱太郎%"
[[excludes]]
keyword = "ニャンだ？フル%"
[[excludes]]
keyword = "遊戯王ＶＲＡＩＮＳ%"
[[excludes]]
keyword = "%はなかっぱ%"
[[excludes]]
keyword = "パッコロリン%"
[[excludes]]
keyword = "オトッペ%"
[[excludes]]
keyword = "ミッキーマウス%"
[[excludes]]
keyword = "しまじろうのわお！%"
[[excludes]]
keyword = "きんだーてれび%"
[[excludes]]
keyword = "アイドルタイム%プリパラ%"
[[excludes]]
keyword = "%ニャッキ！%"
[[excludes]]
keyword = "ミニアニメ　めいたんていラスカル%"
[[excludes]]
keyword = "アニメ%わしも%"
[[excludes]]
keyword = "びじゅチューン！%"
[[excludes]]
keyword = "オトナの一休さん%"
[[excludes]]
keyword = "ピクルスとピーナッツ%"
[[excludes]]
keyword = "トムとジェリー%"
[[excludes]]
keyword = "%ジャム・ザ・ハウスネイル%"
[[excludes]]
keyword = "%うっかりペネロペ%"
[[excludes]]
keyword = "ねこねこ日本史%"
[[excludes]]
keyword = "かみさまみならい%ヒミツのここたま%"
[[excludes]]
keyword = "スナックワールド%"
[[excludes]]
keyword = "%日本の昔ばなし%"
[[excludes]]
keyword = "%シャーミィとかげぼうや%"
[[excludes]]
keyword = "プレキソ英語%"
[[excludes]]
keyword = "ミニアニメ%がんばれ！ルルロロ%"
[[excludes]]
keyword = "ラプンツェル%"
[[excludes]]
keyword="リトル・チャロ%"
[[excludes]]
keyword="ごちそんぐＤＪ%"
[[excludes]]
keyword="アニメ%ピングー%ｉｎ%ザ・シティ%"
[[excludes]]
keyword="%スヌーピー%ショートアニメ%"
[[excludes]]
keyword="%スポンジ・ボブ%"
[[excludes]]
keyword="まんが世界昔ばなし%"
[[excludes]]
keyword="レゴタイム%ニンジャゴー%"
[[excludes]]
keyword="ディズニー・サンデー%"
[[excludes]]
keyword="デュエル・マスターズ%"
[[excludes]]
keyword="%カードファイト！！ヴァンガードＧ%"
[[excludes]]
keyword="アイドル×戦士%ミラクルちゅーんず！%"
[[excludes]]
keyword="げんきげんきノンタン%もういいかい？%"
[[excludes]]
keyword="キラキラ☆プリキュアアラモード%"
[[excludes]]
keyword="仮面ライダービルド%"
[[excludes]]
keyword="宇宙戦隊キュウレンジャー%"
[[excludes]]
keyword="モンスターハンターストーリーズ%"
[[excludes]]
keyword="ちびまる子ちゃん%"
[[excludes]]
keyword="サザエさん%"
[[excludes]]
keyword="ニャンちゅうワールド放送局%"
[[excludes]]
keyword="%ミッフィーのぼうけん%"
[[excludes]]
keyword="きかんしゃトーマス%"
[[excludes]]
keyword="ベイブレードバースト%"
[[excludes]]
keyword="パズドラクロス%"
[[excludes]]
keyword="ＮＡＲＵＴＯ疾風伝%シカマル秘伝%"
[[excludes]]
keyword="戦隊ヒーロー%スキヤキフォース%"
[[excludes]]
keyword="プチプチ・アニメ%モノだらけ！%"
[[excludes]]
keyword="%うさぎのモフィ%"
[[excludes]]
keyword="%[再]%"
[[excludes]]
keyword="%ロボットパルタ%"
[[excludes]]
keyword="%ユニコーンのキュピ%"
[[excludes]]
keyword="リルリルフェアリル〜魔法の鏡〜%"
[[excludes]]
keyword="妖怪ウォッチ%"
[[excludes]]
keyword="それいけ！アンパンマン%"
[[excludes]]
keyword="%ももんがぁモン%"
[[excludes]]
keyword="%ふうせんいぬティニー%"
[[excludes]]
keyword="ビットワールド%"
[[excludes]]
keyword="%カードキャプターさくら%"
[[excludes]]
keyword="遊戯王デュエルモンスターズ%"
[[excludes]]
keyword="フューチャーカード%バディファイトＸ%"
[[excludes]]
keyword="ウルトラマンジード%"
[[excludes]]
keyword="特捜警察ジャンポリス%"
[[excludes]]
keyword="ルパン三世ベストセレクション%"
[[excludes]]
keyword="名探偵コナン%"
[[excludes]]
keyword="アニメサタデー６３０「１００％パスカル先生＆プリプリちぃちゃん！！」%"
[[excludes]]
keyword="トミカハイパーレスキュー%ドライブヘッド%"
[[excludes]]
keyword="ぼのぼの%"
[[excludes]]
keyword="%おさるのジョージ%"
[[excludes]]
keyword="%ひつじのショーン%"
[[excludes]]
keyword="チュウキョ〜くん%"
